name: Release
on:
  release:
    types:
      - published
jobs:
  main:
    name: Default
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: NPM install
        uses: bahmutov/npm-install@v1
        with:
          useLockFile: false

      - name: Build
        run: npm run build

      - name: Create and push Git tag
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git tag "v${{ github.event.release.tag_name }}"
          git push origin "v${{ github.event.release.tag_name }}"

      - name: Release
        run: npm run publish -- --yes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          message: 'release: v${{ github.event.release.tag_name }}'
          author_name: Medžuslovjansky Bot
          author_email: noreply@interslavic.fun
