name: Release
on:
  release:
    types:
      - published
jobs:
  main:
    name: Default
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: NPM install
        uses: bahmutov/npm-install@v1
        with:
          useLockFile: false

      - name: Build
        run: npm run build

      - name: Release
        run: 'npx lerna publish ${{ github.event.release.tag_name }} --yes --no-git-tag-version --no-push --exact --force-publish=*'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          message: 'release: v${{ github.event.release.tag_name }}'
          author_name: Medžuslovjansky Bot
          author_email: noreply@interslavic.fun
